version: "3.8"
services:
  sensu-backend:
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    volumes:
    - "sensu-backend-data:/var/lib/sensu/sensu-backend/etcd"
    command: "sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level debug"
    environment:
      SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: ${user}
      SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: ${pw}
    image: sensu/sensu:latest
    networks:
      - sensu
  sensu-agent:

    image: sensu/sensu:6.1.3
    ports:
      - '3030:3030'
    command: sensu-agent start --backend-url ws://sensu-backend:8081 --deregister --keepalive-interval=5 --keepalive-warning-timeout=10 --subscriptions linux
    networks:
      - sensu
networks:
  sensu:
volumes:
  sensu-backend-data: